version: "3"

networks:
  getitdone:
    external: false

volumes:
  keycloak:
    driver: local
  mongo:
    driver: local

services:
  server1:
    image: server
    build: ./server
    environment:
      - MONGO_URL=mongodb://mongo
      - PROXY_KEYCLOAK_TO_LOCALHOST=true
    depends_on:
      - mongo
      - keycloak
    networks:
      - getitdone
  server2:
    image: server
    build: ./server
    environment:
      - MONGO_URL=mongodb://mongo
      - PROXY_KEYCLOAK_TO_LOCALHOST=true
    depends_on:
      - mongo
      - keycloak
    networks:
      - getitdone
  ui1:
    image: ui
    build: ./ui
    networks:
      - getitdone
  ui2:
    image: ui
    build: ./ui
    networks:
      - getitdone
  load_balancer:
    image: nginx_load_balancer
    build: ./nginx-load-balancer
    networks:
      - getitdone
    ports:
      - "127.0.0.1:8080:80"
    depends_on:
      - ui1
      - ui2
      - server1
      - server2
  keycloak:
    image: keycloak18
    container_name: keycloak
    environment:
    # Demonstration purposes
      - KEYCLOAK_USER=lidl
      - KEYCLOAK_PASSWORD=lidl
    restart: always
    networks:
      - getitdone
    volumes:
      - keycloak:/opt/jboss/keycloak/standalone/data
    ports:
      - "127.0.0.1:8081:8080"
  mongo:
    image: mongo:4
    container_name: mongo
    restart: always
    networks:
      - getitdone
    volumes:
      - mongo:/data/db
    ports:
      - "127.0.0.1:27017:27017"
